Rename repo-base BUILD to BUILD.bazel
This is required because:

- python setup.py (via cibuildwheel) tries to create a directory called `build/` in the project root while building the compiled parts of HEIR.
- MacOS and Windows have case-insensitive file names

So on all platforms except linux, `build/` conflicts with `BUILD`. Thankfully, bazel supports the more verbose filename `BUILD.bazel`.

Cf. https://github.com/google/heir/actions/runs/16148459668

```
error: could not create 'build/lib.macosx-11.0-arm64-cpython-311/heir': Not a directory
```

I was able to reproduce this locally on my MacOS machine, and changing the filename allows the build to proceed.

PiperOrigin-RevId: 780670100