Disable macos-x86 wheel for now
https://github.com/google/heir/actions/runs/23373411993/job/68001321635

Fails at linking `@bison` via `@yosys`

```
 ERROR: /private/var/tmp/_bazel_runner/31b3ff210e07fc40bb7ba4b62e323c0a/external/bison+/BUILD.bazel:961:10: Linking external/bison+/bin/bison [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing CppLink command (from target @@bison+//:bin/bison) external/rules_cc++cc_configure_extension+local_config_cc/cc_wrapper.sh @bazel-out/darwin_x86_64-opt-exec-ST-d57f47055a04/bin/external/bison+/bin/bison-0.params

  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  Undefined symbols for architecture x86_64:
    "_color_mode", referenced from:
        _complain_init_color in libbison.a[7](complain.o)
    "_file_ostream_create", referenced from:
        _complain_init_color in libbison.a[7](complain.o)
    "_handle_color_option", referenced from:
    <SNIP>
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ERROR: /private/var/tmp/_bazel_runner/31b3ff210e07fc40bb7ba4b62e323c0a/external/yosys+/BUILD.bazel:481:11 Compiling external/yosys+/frontends/rtlil/rtlil_parser.tab.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppLink command (from target @@bison+//:bin/bison) external/rules_cc++cc_configure_extension+local_config_cc/cc_wrapper.sh @bazel-out/darwin_x86_64-opt-exec-ST-d57f47055a04/bin/external/bison+/bin/bison-0.params
```

A simple workaround is to disable yosys for the macos-x86 build,
but since macos-x86 is quickly coming to EOL from Apple, seems like
wasted effort to me.